# frozen_string_literal: true

require_relative 'lox_fun_stmt'
require_relative 'lox_variable_expr'
require_relative 'lox_literal_expr'
require_relative 'lox_noop_expr'
require_relative 'lox_call_expr'
require_relative 'lox_grouping_expr'
require_relative 'lox_unary_expr'
require_relative 'lox_binary_expr'
require_relative 'lox_logical_expr'
require_relative 'lox_assign_expr'
require_relative 'lox_block_stmt'
require_relative 'lox_while_stmt'
require_relative 'lox_return_stmt'
require_relative 'lox_print_stmt'
require_relative 'lox_if_stmt'
require_relative 'lox_for_stmt'
require_relative 'lox_var_stmt'
require_relative 'lox_class_stmt'
require_relative 'lox_seq_decl'
